version: "3"
services:
  #tensorflow-test-obere:
 #   image: tensorflow-test-untere
 #   build: ./tensorflow-test
 #   #command: python objectdetection.py           ### Startbefehl der ausgeführt wird nach dem Start
 #   command: bash
 #   privileged: true        ###zugriff auf Hardware
 #   stdin_open: true
 #   tty: true
  #  environment:              ###übergabe von Var für Display und Xsock
 #     - DISPLAY=$DISPLAY       
  #    - SSH_AUTH_SOCK=/tmp/ssh_auth_sock
   #   - XSOCK=/tmp/.X11-unix
  #    - XAUTH=/tmp/.docker.xauth
   #   - QT_X11_NO_MITSHM=1
  #  volumes:                  ###  Mounten von Ordnern in den Dockercontainer
   #   - /home/green/Desktop/Tausch/:/usr/src/app/Tausch/ ## mount nur wenn nicht copiert
   #   - /tmp/.X11-unix/:/tmp/.X11-unix/
   # devices:
   #   - /dev/video0:/dev/video0       ### Übergeben von Webcam
#####mehre Befehle ausführen
#  nvidia-smi-test:                      ### Image beendet sich automatisch wenn der befehl durchgelafufen
#    image: nvidia-smi-test
#    build: ./nvidia-test
#    command: nvidia-smi
#     command: >
#              bash -c "nvidia-smi
#              && cat /Tausch/helloworld.txt"
  tensorflow-sonnet:
    image: tensorflow-test-untere
    build: ./tensorflow-sonnet
    #command: python objectdetection.py           ### Startbefehl der ausgeführt wird nach dem Start
    command: bash
    privileged: true        ###zugriff auf Hardware
    stdin_open: true
    tty: true
    environment:              ###übergabe von Var für Display und Xsock
      - DISPLAY=$DISPLAY       
      - SSH_AUTH_SOCK=/tmp/ssh_auth_sock
      - XSOCK=/tmp/.X11-unix
      - XAUTH=/tmp/.docker.xauth
      - QT_X11_NO_MITSHM=1
    volumes:                  ###  Mounten von Ordnern in den Dockercontainer
      - /home/green/Desktop/Tausch/:/usr/src/app/Tausch/ ## mount nur wenn nicht copiert
      - /tmp/.X11-unix/:/tmp/.X11-unix/
    devices:
      - /dev/video0:/dev/video0       ### Übergeben von Webcam